Repository puppetlabs/facter, pull requests merged in 2020-07, with the labels that each got.

#1949 (maint) Changelog for 4.0.29
  CHANGELOG.md
Labels: maintenance

#1951 (maint) Fix PR links in CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#1950 (FACT-2689) Add hypervisors docker fact
  lib/facts/linux/hypervisors.rb
  lib/facts/linux/hypervisors/docker.rb
  spec/facter/facts/linux/hypervisors/docker_spec.rb
Labels: feature

#1953 (FACT-2692) Add hypervisors lxc fact
  lib/facts/linux/hypervisors/lxc.rb
  spec/facter/facts/linux/hypervisors/lxc_spec.rb
Labels: feature

#1955 (FACT-2691) Add kvm fact on linux
  lib/facts/linux/hypervisors/kvm.rb
  lib/facts_utils/facts_utils.rb
  lib/framework/core/fact/internal/internal_fact_manager.rb
  spec/facter/facts/linux/hypervisors/kvm_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
Labels: feature

#1957 (FACT-2697) Add Xen fact
  lib/facts/linux/hypervisors/xen.rb
  lib/resolvers/xen.rb
  spec/facter/facts/linux/hypervisors/kvm_spec.rb
  spec/facter/facts/linux/hypervisors/xen_spec.rb
  spec/facter/resolvers/xen_spec.rb
Labels: feature

#1956 (FACT-2695) implementation for virtualbox hypervisor fact
  lib/facts/linux/hypervisors/virtualbox.rb
  lib/resolvers/dmi_decode.rb
  spec/facter/facts/linux/hypervisors/virtual_box_spec.rb
  spec/facter/resolvers/dmi_decode_spec.rb
  spec/fixtures/dmi_decode
Labels: feature

#1961 (maint) Read version from version.rb
  Rakefile
  agent/facter-ng.gemspec
  facter.gemspec
  install.rb
  lib/facter.rb
  lib/facter/VERSION
  lib/facter/config/config.rb
  lib/facter/custom_facts/core/file_loader.rb
  lib/facter/custom_facts/util/loader.rb
  lib/facter/custom_facts/version.rb
  lib/facter/framework/cli/cli.rb
  lib/facter/resolvers/facterversion_resolver.rb
  lib/facter/version.rb
  spec/custom_facts/util/loader_spec.rb
  spec/facter/resolvers/facterversion_resolver_spec.rb
Labels: maintenance

#1969 (FACT-2703) Return nil when product name is not recognized
  lib/facter/facts/linux/is_virtual.rb
  lib/facter/facts/linux/virtual.rb
  spec/facter/facts/linux/is_virtual_spec.rb
  spec/facter/facts/linux/virtual_spec.rb
Labels: bugfix

#1968 (FACT-2690) Added Hyper-V fact for Linux
  lib/facter/facts/linux/hypervisors/hyper_v.rb
  spec/facter/facts/linux/hypervisors/hyper_v_spec.rb
Labels: feature

#1971 (FACT-2673) Fix mountpoints logic for osx
  lib/facter/resolvers/macosx/mountpoints_resolver.rb
  spec/facter/resolvers/macosx/mountpoints_resolver_spec.rb
Labels: bugfix

#1947 (FACT-2656) Add solaris networking facts
  README.md
  lib/facter/facts/solaris/dhcp_servers.rb
  lib/facter/facts/solaris/interfaces.rb
  lib/facter/facts/solaris/ipaddress6_interfaces.rb
  lib/facter/facts/solaris/ipaddress_interfaces.rb
  lib/facter/facts/solaris/macaddress_interfaces.rb
  lib/facter/facts/solaris/mtu_interfaces.rb
  lib/facter/facts/solaris/netmask6_interfaces.rb
  lib/facter/facts/solaris/netmask_interfaces.rb
  lib/facter/facts/solaris/network6_interfaces.rb
  lib/facter/facts/solaris/network_interfaces.rb
  lib/facter/facts/solaris/networking/dhcp.rb
  lib/facter/facts/solaris/networking/interfaces.rb
  lib/facter/facts/solaris/networking/ip6.rb
  lib/facter/facts/solaris/networking/mac.rb
  lib/facter/facts/solaris/networking/mtu.rb
  lib/facter/facts/solaris/networking/netmask.rb
  lib/facter/facts/solaris/networking/netmask6.rb
  lib/facter/facts/solaris/networking/network.rb
  lib/facter/facts/solaris/networking/network6.rb
  lib/facter/facts/solaris/networking/primary.rb
  lib/facter/resolvers/solaris/ffi/ffi.rb
  lib/facter/resolvers/solaris/ffi/functions.rb
  lib/facter/resolvers/solaris/ffi/structs.rb
  lib/facter/resolvers/solaris/networking_resolver.rb
  spec/facter/facts/solaris/dhcp_servers_spec.rb
  spec/facter/facts/solaris/interfaces_spec.rb
  spec/facter/facts/solaris/ipaddress6_interfaces_spec.rb
  spec/facter/facts/solaris/ipaddress_interfaces_spec.rb
  spec/facter/facts/solaris/macaddress_interfaces_spec.rb
  spec/facter/facts/solaris/mtu_interfaces_spec.rb
  spec/facter/facts/solaris/netmask6_interfaces_spec.rb
  spec/facter/facts/solaris/netmask_interfaces_spec.rb
  spec/facter/facts/solaris/network6_interfaces_spec.rb
  spec/facter/facts/solaris/network_interfaces_spec.rb
  spec/facter/facts/solaris/networking/dhcp_spec.rb
  spec/facter/facts/solaris/networking/interfaces_spec.rb
  spec/facter/facts/solaris/networking/ip6_spec.rb
  spec/facter/facts/solaris/networking/mac_spec.rb
  spec/facter/facts/solaris/networking/mtu_spec.rb
  spec/facter/facts/solaris/networking/netmask6_spec.rb
  spec/facter/facts/solaris/networking/netmask_spec.rb
  spec/facter/facts/solaris/networking/network6_spec.rb
  spec/facter/facts/solaris/networking/network_spec.rb
  spec/facter/facts/solaris/networking/primary_spec.rb
  spec/mocks/ffi_mock.rb
Labels: feature

#1974 (maint) Fix Solaris networking resolver
  lib/facter/resolvers/solaris/networking_resolver.rb
Labels: maintenance

#1975 (maint) Fix custom facts loading
  lib/facter/custom_facts/util/loader.rb
  lib/facter/version.rb
  spec/custom_facts/util/loader_spec.rb
Labels: maintenance

#1976 (maint) Allow comparison between Facter::Core::Aggregate objects
  lib/facter/custom_facts/core/aggregate.rb
  spec/custom_facts/core/aggregate_spec.rb
Labels: maintenance

#1973 (maint) Changelog for 4.0.30
  CHANGELOG.md
  lib/facter/version.rb
Labels: maintenance

#1977 (maint) handle Time and Symbol in executable facts
  .rubocop.yml
  lib/facter/custom_facts/util/parser.rb
  spec/custom_facts/util/parser_spec.rb
Labels: bugfix

#1982 (FACT-2702) Fix system_profiler legacy facts
  lib/facter/facts/macosx/system_profiler/hardware_uuid.rb
  lib/facter/facts/macosx/system_profiler/l2_cache_per_core.rb
  lib/facter/facts/macosx/system_profiler/memory.rb
  lib/facter/facts/macosx/system_profiler/processor_name.rb
  lib/facter/facts/macosx/system_profiler/processors.rb
  spec/facter/facts/macosx/system_profiler/hardware_uuid_spec.rb
  spec/facter/facts/macosx/system_profiler/l2_cache_per_core_spec.rb
  spec/facter/facts/macosx/system_profiler/memory_spec.rb
  spec/facter/facts/macosx/system_profiler/processor_name_spec.rb
  spec/facter/facts/macosx/system_profiler/processors_spec.rb
Labels: bugfix

#1984 (FACT-2708) Add man pages
  Gemfile
  agent/facter-ng.gemspec
  facter.gemspec
  install.rb
  lib/facter/framework/cli/cli.rb
  lib/facter/templates/man.erb
  man/man8/facter.8
  tasks/manpages.rake
Labels: feature

#1990 (maint) Fixed --color acceptance test
  acceptance/tests/options/color.rb
Labels: maintenance

#1985 (FACT-2712) Add integration test for loading custom facts
  acceptance/tests/custom_facts/load_custom_fact_from_lib_facter.rb
Labels: maintenance

#1988 (FACT-2710) Correctly display vmware info
  lib/facter/facts/linux/hypervisors/vmware.rb
  spec/facter/facts/linux/hypervisors/vmware_spec.rb
Labels: bugfix

#1991 (maint) Fixed --color acceptance test
  acceptance/tests/options/color.rb
Labels: maintenance

#1986 (FACT-2687) --trace shows backtrace for core facts
  lib/facter.rb
  lib/facter/framework/core/fact/internal/internal_fact_manager.rb
  lib/facter/framework/core/options.rb
  lib/facter/framework/core/options/option_store.rb
  lib/facter/framework/logging/logger.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
  spec/framework/core/options/option_store_spec.rb
  spec/framework/logging/logger_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#1989 (FACT-2707) Fix linux/virtual tests
  spec/facter/facts/linux/virtual_spec.rb
Labels: maintenance

#1987 (FACT-2220) Add Aix disks fact
  lib/facter/facts/aix/disks.rb
  lib/facter/resolvers/aix/disks.rb
  lib/facter/resolvers/aix/partitions.rb
  lib/facter/resolvers/aix/utils/info_extractor.rb
  spec/facter/facts/aix/disks_spec.rb
  spec/facter/resolvers/aix/disks_spec.rb
  spec/fixtures/lspv_disk_output
  spec/fixtures/lspv_output
Labels: feature

#1994 (FACT-2230) Add Aix memory facts
  lib/facter/facts/aix/memory/swap/available.rb
  lib/facter/facts/aix/memory/swap/available_bytes.rb
  lib/facter/facts/aix/memory/swap/capacity.rb
  lib/facter/facts/aix/memory/swap/total.rb
  lib/facter/facts/aix/memory/swap/total_bytes.rb
  lib/facter/facts/aix/memory/swap/used.rb
  lib/facter/facts/aix/memory/swap/used_bytes.rb
  lib/facter/facts/aix/memory/system/available.rb
  lib/facter/facts/aix/memory/system/available_bytes.rb
  lib/facter/facts/aix/memory/system/capacity.rb
  lib/facter/facts/aix/memory/system/total.rb
  lib/facter/facts/aix/memory/system/total_bytes.rb
  lib/facter/facts/aix/memory/system/used.rb
  lib/facter/facts/aix/memory/system/used_bytes.rb
  lib/facter/resolvers/aix/memory.rb
  spec/facter/facts/aix/memory/swap/available_bytes_spec.rb
  spec/facter/facts/aix/memory/swap/available_spec.rb
  spec/facter/facts/aix/memory/swap/capacity_spec.rb
  spec/facter/facts/aix/memory/swap/total_bytes_spec.rb
  spec/facter/facts/aix/memory/swap/total_spec.rb
  spec/facter/facts/aix/memory/swap/used_bytes_spec.rb
  spec/facter/facts/aix/memory/swap/used_spec.rb
  spec/facter/facts/aix/memory/system/available_bytes_spec.rb
  spec/facter/facts/aix/memory/system/available_spec.rb
  spec/facter/facts/aix/memory/system/capacity_spec.rb
  spec/facter/facts/aix/memory/system/total_bytes_spec.rb
  spec/facter/facts/aix/memory/system/total_spec.rb
  spec/facter/facts/aix/memory/system/used_bytes_spec.rb
  spec/facter/facts/aix/memory/system/used_spec.rb
  spec/facter/resolvers/aix/memory_spec.rb
  spec/fixtures/svmon_content
Labels: feature

#1996 (FACT-2718) Block custom facts
  .github/actions/presuite.rb
  acceptance/tests/custom_facts/block_custom_fact.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
  spec/framework/core/fact_loaders/fact_loader_spec.rb
Labels: feature

#2000 (maint) Add changelog and bump version.
  CHANGELOG.md
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2001 (maint) add gem version to README.md
  README.md
Labels: maintenance

#1993 (FACT-2699) augeas fact for OSX is not resolved
  lib/facter/resolvers/augeas_resolver.rb
  spec/facter/resolvers/augeas_resolver_spec.rb
  spec/mocks/augeas.rb
  spec/mocks/kernel_mock.rb
Labels: bugfix

#1998 (FACT-2717) Block external facts
  .rubocop.yml
  acceptance/tests/external_facts/block_external_facts.rb
  lib/facter/custom_facts/util/directory_loader.rb
  spec/custom_facts/util/directory_loader_spec.rb
Labels: feature

#2002 (FACT-2733) Fix networking on Fedora 32
  lib/facter/resolvers/networking_linux_resolver.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
Labels: bugfix

#2003 (FACT-2734) Return nil codename if we cannot determine it from /etc/redhat_release
  lib/facter/resolvers/redhat_release_resolver.rb
  spec/facter/resolvers/redhat_release_resolver_spec.rb
Labels: bugfix

#2005 (maint) Changelog for release 4.0.32 and version bump.
  CHANGELOG.md
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2006 (FACT-2699-2) Catch augeas exception in resolver.
  lib/facter/resolvers/augeas_resolver.rb
  spec/facter/resolvers/augeas_resolver_spec.rb
Labels: bugfix

#2007 (FACT-2699) Revert "(FACT-2699) Catch augeas exception in resolver."
  lib/facter/resolvers/augeas_resolver.rb
  spec/facter/resolvers/augeas_resolver_spec.rb
Labels: maintenance
