Repository puppetlabs/facter, pull requests merged in 2020-10, with the labels that each got.

#2115 (maint) Add changelog for release 4.0.41
  CHANGELOG.md
Labels: maintenance

#2118 (FACT-2824) Add unit tests for VirtualDetector
  .rubocop_todo.yml
  spec/facter/facts_utils/virtual_detector_spec.rb
Labels: maintenance

#2109 (FACT-2805) Read available memory from MemAvailable
  lib/facter/resolvers/memory_resolver.rb
  spec/facter/resolvers/memory_resolver_spec.rb
  spec/fixtures/meminfo_missing_available
Labels: bugfix

#2119 (FACT-2792) Show not supported message for facter -p
  lib/facter/framework/cli/cli.rb
Labels: feature

#2122 (maint) Update regex for os.macosx.build
  acceptance/lib/facter/acceptance/base_fact_utils.rb
Labels: maintenance

#2114 (maint) Avoid deadlock of Facter::Core::Execution.execute
  .github/workflows/acceptance_tests.yml
  acceptance/tests/custom_facts/long_stderr_with_time_limit.rb
  acceptance/tests/custom_facts/time_limit_for_execute_command.rb
  lib/facter/custom_facts/core/execution/base.rb
  lib/facter/resolvers/aix/os_level.rb
  spec/facter/resolvers/aix/os_level_spec.rb
Labels: bugfix

#2123 (maint) Fix external fact cache
  lib/facter/framework/core/cache_manager.rb
  spec/facter/cache_manager_spec.rb
Labels: bugfix

#2126 (maint) changelog for 4.0.42
  CHANGELOG.md
Labels: maintenance

#2125 (FACT-2810) Fix dmi.board_asset_tag and dhcp
  lib/facter/resolvers/dmi_resolver.rb
  lib/facter/resolvers/networking_linux_resolver.rb
  spec/facter/resolvers/dmi_resolver_spec.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
Labels: bugfix

#1992 (FACT-2704) change all acceptance to risk:high
  acceptance/lib/facter/acceptance/user_fact_utils.rb
  acceptance/tests/custom_facts/conflicts_with_builtin_fact.rb
  acceptance/tests/external_facts/env_var_overrides_external_fact.rb
  acceptance/tests/facts/facterversion.rb
  acceptance/tests/options/config_file/blocklist_from_puppet_facts.rb
  acceptance/tests/options/config_file/custom_dir_overridden_by_cli_custom_dir.rb
  acceptance/tests/options/config_file/custom_facts.rb
  acceptance/tests/options/config_file/custom_facts_list.rb
  acceptance/tests/options/config_file/debug_override_config_file.rb
  acceptance/tests/options/config_file/external_dir_conflicts_with_cli_no_external_facts.rb
  acceptance/tests/options/config_file/external_dir_overridden_by_cli_external_dir.rb
  acceptance/tests/options/config_file/external_facts.rb
  acceptance/tests/options/config_file/external_facts_list.rb
  acceptance/tests/options/config_file/no_custom_facts_and_custom_dir.rb
  acceptance/tests/options/config_file/no_custom_facts_and_facterlib.rb
  acceptance/tests/options/config_file/no_custom_facts_and_load_path.rb
  acceptance/tests/options/config_file/no_external_facts.rb
  acceptance/tests/options/config_file/no_external_facts_and_external_dir.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_json_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_text_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_yaml_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_json_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_external_text_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_external_yaml_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_facts_creates_json_cache_file.rb
  acceptance/tests/options/config_file/ttls_puppet_facts_creates_json_for_cached_facts.rb
  acceptance/tests/options/config_file/verbose.rb
  acceptance/tests/options/custom_facts.rb
  acceptance/tests/options/custom_facts_facterlib.rb
  acceptance/tests/options/custom_facts_load_path.rb
  acceptance/tests/options/external_facts.rb
  acceptance/tests/options/list_block_groups.rb
  acceptance/tests/options/list_cache_groups.rb
  acceptance/tests/options/no_block.rb
  acceptance/tests/options/no_color.rb
  acceptance/tests/options/no_custom_facts_and_custom_dir.rb
  acceptance/tests/options/no_custom_facts_and_facterlib.rb
  acceptance/tests/options/no_custom_facts_and_load_path.rb
  acceptance/tests/options/no_external_facts.rb
  acceptance/tests/options/no_external_facts_and_external_dir.rb
Labels: maintenance

#2121 (FACT-2817) Only invalidate session cache on clear and reset.
  acceptance/tests/session_cached_is_not_refershed_in_session.rb
  custom_facts/my_custom_fact.rb
  lib/facter.rb
Labels: bugfix

#2128 (maint) Fix virtual_detector
  lib/facter/facts_utils/virtual_detector.rb
  spec/facter/facts_utils/virtual_detector_spec.rb
Labels: bugfix

#2116 (FACT-2809) Fixed output differences on solaris
  lib/facter/facts/solaris/zones.rb
  lib/facter/resolvers/mountpoints_resolver.rb
  lib/facter/resolvers/solaris/mountpoints.rb
  lib/facter/resolvers/solaris/networking.rb
  spec/facter/facts/solaris/zones_spec.rb
  spec/facter/resolvers/mountpoints_resolver_spec.rb
  spec/facter/resolvers/solaris/mountpoints_spec.rb
  spec/mocks/sys_filesystem_mock.rb
Labels: bugfix

#2127 (FACT-2806) Fix physicalprocessorcount
  lib/facter/resolvers/processors_resolver.rb
  spec/facter/resolvers/processors_resolver_spec.rb
  spec/fixtures/cpuinfo_arm64
Labels: bugfix

#2124 (FACT-2438_docu) adjusted the documentation for private and public apis
  lib/facter.rb
  lib/facter/custom_facts/core/aggregate.rb
  lib/facter/custom_facts/core/execution.rb
  lib/facter/custom_facts/util/resolution.rb
Labels: maintenance

#2131 (maint) Revert facter -p until we upgrade modules that use facter -p.
  lib/facter/framework/cli/cli.rb
Labels: maintenance

#2132 (maint) Update changelog
  CHANGELOG.md
Labels: maintenance

#2136 (maint) Return facts in resolve
  lib/facter.rb
Labels: maintenance

#2133 (FACT-2806) Fix os.release.minor on amazon 6
  lib/facter/facts/rhel/os/release.rb
Labels: bugfix

#2129 (FACT-2643) Add test to verify timeout on resolution
  acceptance/tests/custom_facts/resolution_timeout_option.rb
Labels: maintenance

#2135 (FACT-2832) Use full path for augparse command
  lib/facter/resolvers/augeas_resolver.rb
  spec/facter/resolvers/augeas_resolver_spec.rb
Labels: bugfix

#2141 (maint) update maintainability and test coverage badge
  README.md
Labels: maintenance

#2137 (FACT-2827) Reset ttls settings on OptionStore reset
  lib/facter/framework/core/options/option_store.rb
  spec/framework/core/options/option_store_spec.rb
Labels: maintenance

#2130 (FACT-2811)part 1. Fixed solaris virtual, is_virtual tests, options_store an…
  lib/facter/framework/core/options/option_store.rb
  lib/facter/resolvers/solaris/dmi.rb
  spec/facter/facts/solaris/is_virtual_spec.rb
  spec/facter/facts/solaris/virtual_spec.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/facter/resolvers/windows/virtualization_resolver_spec.rb
  spec/facter/util/file_helper_spec.rb
  spec/framework/core/options/option_store_spec.rb
  spec/framework/detector/os_detector_spec.rb
Labels: maintenance

#2134 (FACT-2815) Added timing for cached facts
  lib/facter/framework/benchmarking/timer.rb
  lib/facter/framework/core/cache_manager.rb
  spec/facter/cache_manager_spec.rb
  spec/facter/framework/benchmarking/timer_spec.rb
Labels: bugfix

#2143 (FACT-2811) part2. Fixed all unit tests which failed with rspec --order rand
  check.sh
  lib/facter/custom_facts/util/fact.rb
  lib/facter/framework/config/fact_groups.rb
  lib/facter/framework/core/options/option_store.rb
  lib/facter/resolvers/bsd/processors.rb
  lib/facter/resolvers/freebsd/geom_resolver.rb
  lib/facter/resolvers/freebsd/processors.rb
  lib/facter/resolvers/partitions.rb
  lib/facter/resolvers/solaris/networking.rb
  lib/facter/resolvers/solaris/os_release.rb
  lib/facter/resolvers/ssh_resolver.rb
  spec/custom_facts/util/collection_spec.rb
  spec/facter/facter_spec.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/framework/core/options/option_store_spec.rb
Labels: maintenance

#2140 (FACT-2826) Added Facter.flush
  acceptance/tests/facter_flush.rb
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: maintenance

#2147 (FACT-2834) Dinamically get AIX proc number
  lib/facter/resolvers/aix/architecture_resolver.rb
  spec/facter/resolvers/aix/architecture_resolver_spec.rb
Labels: bugfix

#2146 (FACT-2829) Fixed partitions and mount points facts
  lib/facter/resolvers/mountpoints_resolver.rb
  lib/facter/resolvers/partitions.rb
  spec/facter/resolvers/mountpoints_resolver_spec.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/fixtures/blkid_output_root_has_partuuid
  spec/fixtures/cmdline_root_device_partuuid
Labels: bugfix

#2144 (FACT-2841) drop internal config files
  .rubocop.yml
  lib/facter/config.rb
  lib/facter/fact_groups.conf
  lib/facter/framework/config/fact_groups.rb
  lib/facter/framework/detector/os_hierarchy.rb
  lib/facter/os_hierarchy.json
  spec/framework/config/fact_groups_spec.rb
  spec/framework/detector/os_hierarchy_spec.rb
Labels: maintenance

#2145 Added disk_type field to disk fact
  lib/facter/resolvers/disk_resolver.rb
  spec/facter/resolvers/disk_resolver_spec.rb
Labels: community, feature

#2149 (maint) Use strings instead of symbols for os names.
  lib/facter/config.rb
Labels: bugfix

#2148 (maint) Changelog for 4.0.44 release
  CHANGELOG.md
Labels: maintenance

#2139 (FACT-2835) Extract external fact stderr logging outside of Facter::Util::Resolution.exec
  acceptance/tests/custom_facts/long_stderr_with_time_limit.rb
  lib/facter/custom_facts/core/execution.rb
  lib/facter/custom_facts/core/execution/base.rb
  lib/facter/custom_facts/util/parser.rb
  spec/custom_facts/core/execution/fact_manager_spec.rb
  spec/custom_facts/util/parser_spec.rb
Labels: bugfix

#2152 (maint) Pass on_fail to execute_command
  lib/facter/custom_facts/util/parser.rb
  spec/custom_facts/util/parser_spec.rb
Labels: bugfix

#2156 (maint) update puppet facts tests
  acceptance/tests/facts/validate_file_system_size_bytes.rb
  acceptance/tests/options/config_file/blocklist_from_puppet_facts.rb
  acceptance/tests/options/config_file/ttls_puppet_facts_honors_cached_facts.rb
Labels: maintenance

#2157 (FACT-2839) Added extra check for TTLS keys
  lib/facter/framework/core/cache_manager.rb
  spec/facter/cache_manager_spec.rb
Labels: maintenance

#2155 (maint) Fix execute_command parameter passing
  lib/facter/custom_facts/core/execution.rb
  lib/facter/custom_facts/util/parser.rb
  spec/custom_facts/util/parser_spec.rb
Labels: maintenance

#2151 (maint) Improve FreeBSD version detection
  lib/facter/resolvers/freebsd/freebsd_version_resolver.rb
  spec/facter/resolvers/freebsd/freebsd_version_resolver_spec.rb
Labels: bugfix, community

#2153 (FACT-2842) Fix ldom facts on Solaris
  lib/facter/facts/solaris/hypervisors/ldom.rb
  lib/facter/facts/solaris/ldom.rb
  lib/facter/resolvers/solaris/ldom.rb
  spec/facter/facts/solaris/hypervisors/ldom_spec.rb
  spec/facter/facts/solaris/ldom_spec.rb
Labels: bugfix

#2159 (FACT-2846) Fix networking fact when peer ip
  lib/facter/resolvers/networking_linux_resolver.rb
  lib/facter/resolvers/utils/networking.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
  spec/facter/resolvers/utils/networking_spec.rb
  spec/fixtures/ip_o_address_with_peer
Labels: bugfix
