Repository puppetlabs/facter, pull requests merged in 2020-11, with the labels that each got.

#2160 (maint) add license attribute to gemspec
  facter.gemspec
Labels: maintenance

#2164 (FACT-2792) Show warning message when -p is used.
  lib/facter/framework/cli/cli.rb
Labels: maintenance

#2161 (maint) Fix fact augmenter
  lib/facter/framework/core/fact_augmenter.rb
Labels: maintenance

#2165 (FACT-2792) Show warning and facter facts when using -p argument
  lib/facter/framework/cli/cli.rb
Labels: maintenance

#2166 (maint) Move benchmarking of core facts to CoreFact class.
  lib/facter/framework/core/fact/internal/core_fact.rb
  lib/facter/framework/core/fact/internal/internal_fact_manager.rb
Labels: maintenance

#2167 (FACT-2853) Replace _ with - in help.
  acceptance/tests/options/help.rb
  lib/facter/framework/cli/cli.rb
Labels: bugfix

#2168 (FACT-2854) Empty string in blocklist should not block all facts
  acceptance/tests/options/blocklist_no_regex.rb
  acceptance/tests/options/blocklist_with_regex.rb
  acceptance/tests/options/empty_string_in_blocklist.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
Labels: bugfix

#2171 (maint) Bump facter to 4.0.45
  agent/facter-ng.gemspec
  facter.gemspec
  tasks/commits.rake
Labels: maintenance

#2175 (maint) Remove cache file if it is invalid
  acceptance/tests/custom_facts/cached_custom_fact.rb
  acceptance/tests/custom_facts/weighted_cached_custom_facts.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_json_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_text_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_yaml_output.rb
  acceptance/tests/options/config_file/ttls_cached_external_json_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_external_text_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_external_yaml_resolver.rb
  acceptance/tests/options/config_file/ttls_cached_facts_read_from_the_cached_value.rb
  acceptance/tests/options/config_file/ttls_cached_facts_that_are_empty_return_an_empty_value.rb
  acceptance/tests/options/config_file/ttls_cached_individual_fact_name.rb
  acceptance/tests/options/config_file/ttls_puppet_facts_honors_cached_facts.rb
  facter.conf
  lib/facter/custom_facts/util/directory_loader.rb
  lib/facter/framework/config/fact_groups.rb
  lib/facter/framework/core/cache_manager.rb
  lib/facter/framework/core/fact_manager.rb
  spec/custom_facts/util/directory_loader_spec.rb
  spec/facter/cache_manager_spec.rb
Labels: bugfix

#2179 (maint) Fixed multiple cache file rewrite
  acceptance/tests/options/config_file/ttls_external_facts_in_custom_groups.rb
  lib/facter/framework/core/cache_manager.rb
Labels: bugfix

#2183 (FACT-2863) Removed puppetversion fact
  lib/facter/facts/aix/interfaces.rb
  lib/facter/facts/aix/puppet_version.rb
  lib/facter/facts/freebsd/puppet_version.rb
  lib/facter/facts/linux/dhcp_servers.rb
  lib/facter/facts/linux/interfaces.rb
  lib/facter/facts/linux/puppet_version.rb
  lib/facter/facts/macosx/dhcp_servers.rb
  lib/facter/facts/macosx/interfaces.rb
  lib/facter/facts/macosx/puppet_version.rb
  lib/facter/facts/solaris/dhcp_servers.rb
  lib/facter/facts/solaris/interfaces.rb
  lib/facter/facts/solaris/puppet_version.rb
  lib/facter/facts/windows/dhcp_servers.rb
  lib/facter/facts/windows/interfaces.rb
  lib/facter/facts/windows/puppet_version.rb
  lib/facter/resolvers/puppet_version_resolver.rb
  spec/facter/facts/aix/puppet_version_spec.rb
  spec/facter/facts/freebsd/puppet_version_spec.rb
  spec/facter/facts/linux/puppet_version_spec.rb
  spec/facter/facts/macosx/puppet_version_spec.rb
  spec/facter/facts/solaris/puppet_version_spec.rb
  spec/facter/facts/windows/puppet_version_spec.rb
Labels: maintenance

#2184 (FACT-2298) Delete rake task that created facts and rspec
  tasks/create_fact.rake
  tasks/fact_generator/fact.erb
  tasks/fact_generator/fact_creator.rb
  tasks/fact_generator/fact_spec.erb
  tasks/fact_generator/facts.json
  tasks/fact_generator/path.rb
Labels: maintenance

#2173 (FACT-2850) Don't show nil custom facts
  lib/facter.rb
  lib/facter/models/fact_collection.rb
  spec/facter/model/fact_collection_spec.rb
Labels: bugfix

#2181 (FACT-2860) Agent release pipeline updates
  Gemfile
  Rakefile
  ext/build_defaults.yaml
  ext/project_data.yaml
  facter.gemspec
Labels: maintenance

#2193 (FACT-2869) is_virtual fact should be boolean
  lib/facter/facts/linux/is_virtual.rb
  spec/facter/facts/linux/is_virtual_spec.rb
Labels: bugfix

#2182 (maint) Add more cache acceptance tests
  acceptance/tests/options/config_file/ttls/cached_all_types_of_facts.rb
  acceptance/tests/options/config_file/ttls/cached_nested_custom_facts.rb
  acceptance/tests/options/config_file/ttls/cached_nested_external_facts.rb
  acceptance/tests/options/config_file/ttls/empty_ttls_does_not_delete_cache.rb
Labels: maintenance

#2190 (FACT-2851) Log useful error message when fact cannot be added to fact collection
  lib/facter/models/fact_collection.rb
  spec/facter/model/fact_collection_spec.rb
Labels: maintenance

#2194 (FACT-2856) Facter fails when interface name is not UTF-8
  lib/facter/framework/core/file_loader.rb
  lib/facter/resolvers/solaris/networking.rb
  lib/facter/resolvers/utils/networking/dhcp.rb
  lib/facter/resolvers/utils/networking/networking.rb
  lib/facter/resolvers/utils/networking/primary_interface.rb
  lib/facter/resolvers/windows/memory_resolver.rb
  spec/facter/resolvers/utils/networking/networking_spec.rb
Labels: bugfix

#2189 (maint) Added some new fact groups
  lib/facter/config.rb
Labels: maintenance

#2188 (FACT-2864) Add the ldom legacy facts
  lib/facter/facts/solaris/ldom.rb
  spec/facter/facts/solaris/ldom_spec.rb
Labels: feature

#2191 (FACT-2866) Added cache acceptance tests
  acceptance/tests/options/config_file/ttls_cache_missing_facts.rb
  acceptance/tests/options/config_file/ttls_cache_system_uptime.rb
Labels: maintenance

#2198 (FACT-2870) Don't split legacy fact names
  lib/facter/models/fact_collection.rb
  spec/facter/model/fact_collection_spec.rb
Labels: bugfix

#2192 (FACT-2843) Add scope6 fact for every binding
  lib/facter/resolvers/utils/networking/networking.rb
  spec/facter/resolvers/aix/networking_resolver_spec.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
  spec/facter/resolvers/networking_resolver_spec.rb
  spec/facter/resolvers/utils/networking/networking_spec.rb
  spec/facter/resolvers/windows/networking_resolver_spec.rb
Labels: feature
