Repository puppetlabs/facter, pull requests merged in 2020-09, with the labels that each got.

#2055 (FACT-2754) Add os.distro release legacy facts
  lib/facter/facts/debian/os/distro/release.rb
  spec/facter/facts/debian/os/distro/release_spec.rb
Labels: bugfix

#2056 (FACT-2729) Add Solaris is_virtual fact
  lib/facter/facts/linux/is_virtual.rb
  lib/facter/facts/solaris/is_virtual.rb
  lib/facter/facts_utils/facts_utils.rb
  spec/facter/facts/solaris/is_virtual_spec.rb
Labels: feature

#2057 (FACT-2771) Fix Solaris kernelmajversion fact
  lib/facter/facts/solaris/kernelmajversion.rb
  spec/facter/facts/solaris/kernelmajversion_spec.rb
Labels: bugfix

#2058 (FACT-2457) Display newlines in values
  lib/facter/framework/formatters/legacy_fact_formatter.rb
  spec/framework/formatters/legacy_fact_formatter_spec.rb
Labels: bugfix

#2059 (FACT-2773) Added board_asset_tag fact for linux
  lib/facter/facts/linux/dmi/board/asset_tag.rb
  lib/facter/resolvers/dmi_resolver.rb
  spec/facter/facts/linux/dmi/board/asset_tag_spec.rb
  spec/facter/resolvers/dmi_resolver_spec.rb
Labels: feature

#2062 (maint)changelog
  CHANGELOG.md
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2061 (FACT-1380) Restore --timing option to native facter
  lib/facter/custom_facts/util/directory_loader.rb
  lib/facter/custom_facts/util/fact.rb
  lib/facter/framework/benchmarking/timer.rb
  lib/facter/framework/cli/cli.rb
  lib/facter/framework/core/fact/internal/internal_fact_manager.rb
  lib/facter/framework/core/file_loader.rb
  lib/facter/framework/core/options/option_store.rb
  spec/facter/framework/benchmarking/timer_spec.rb
  spec/framework/core/options/option_store_spec.rb
Labels: feature

#2069 (maint) fix File.expand_path error on Windows github actions
  spec/custom_facts/util/config_spec.rb
Labels: maintenance

#2065 (FACT-2781) Fix filesystems on osx
  lib/facter/resolvers/macosx/filesystems_resolver.rb
  spec/facter/resolvers/macosx/filesystems_resolver_spec.rb
  spec/fixtures/macosx_filesystems
Labels: bugfix

#2063 (FACT-2777) Fix lsbdist facts on ubuntu
  lib/facter/facts/ubuntu/lsbdistrelease.rb
  spec/facter/facts/ubuntu/lsbdistrelease_spec.rb
Labels: bugfix

#2064 (maint) Change how facter from puppet agent is replaced
  .github/actions/presuite.rb
Labels: maintenance

#2070 (maint) Fix internal fact loader
  lib/facter/framework/core/fact_loaders/internal_fact_loader.rb
Labels: maintenance

#2071 (maint) On El5 some info are missing from meminfo
  lib/facter/resolvers/memory_resolver.rb
  spec/facter/resolvers/memory_resolver_spec.rb
  spec/fixtures/rhel5_memory
Labels: maintenance

#2073 (maint) move to main branch
  .github/workflows/acceptance_tests.yml
  .github/workflows/checks.yaml
  .github/workflows/coverage.yaml
  .github/workflows/unit_tests.yaml
  README.md
  scripts/generate_changelog.rb
Labels: maintenance

#2074 (maint) merge 4.x to main
  lib/facter/resolvers/memory_resolver.rb
  spec/facter/resolvers/memory_resolver_spec.rb
  spec/fixtures/rhel5_memory
Labels: maintenance

#2067 (FACT-2551) Defaulting resolver keys to nil after no resolution
  lib/facter/resolvers/aix/disks.rb
  lib/facter/resolvers/aix/memory.rb
  lib/facter/resolvers/aix/partitions.rb
  lib/facter/resolvers/base_resolver.rb
  spec/facter/resolvers/base_resolver_spec.rb
  spec/facter/resolvers/processors_resolver_spec.rb
Labels: maintenance

#2072 (FACT-2783) Updated how osx mountpoints are calculated
  lib/facter/resolvers/macosx/mountpoints_resolver.rb
  spec/facter/resolvers/macosx/mountpoints_resolver_spec.rb
Labels: bugfix

#2077 (FACT-2785) partitions.<partition_name>.mount has wrong value on sles15-64
  lib/facter/facts/linux/partitions.rb
  spec/facter/facts/linux/partitions_spec.rb
Labels: bugfix

#2076 (FACT-2776) Fix Linux partitions fact
  .rubocop.yml
  lib/facter/resolvers/partitions.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/fixtures/lsblk_output
Labels: bugfix

#2085 (FACT-2319) Added debugonce method
  lib/facter.rb
  lib/facter/framework/logging/logger.rb
  spec/facter/facter_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: feature

#2081 (FACT-2389) Modified the win32 mocks to better reflect reality
  spec/facter/resolvers/windows/netkvm_resolver_spec.rb
  spec/mocks/win32_mock.rb
  spec/mocks/win32_registry_error_mock.rb
Labels: maintenance

#2088 (FACT-2327) added list method
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: feature

#2084 (FACT-2320) Added warnonce method
  lib/facter.rb
  lib/facter/framework/logging/logger.rb
  spec/facter/facter_spec.rb
Labels: feature

#2086 (FACT-2784) Fixed rhel os release fact
  lib/facter/facts/rhel/os/release.rb
  spec/facter/facts/rhel/os/release_spec.rb
Labels: bugfix

#2083 (FACT-2315) Added warn method to facter api
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: feature

#2082 (FACT-2746) Added cloud resolver
  lib/facter/facts/linux/cloud.rb
  lib/facter/resolvers/cloud.rb
  spec/facter/resolvers/cloud_spec.rb
  spec/fixtures/dhclient_rhel_lease_8
Labels: feature

#2092 (maint) Fix facter install on windows.
  .github/actions/presuite.rb
  .github/workflows/acceptance_tests.yml
Labels: maintenance

#2093 (FACT-2802) Fix Cloud resolver
  lib/facter/resolvers/cloud.rb
  spec/facter/resolvers/cloud_spec.rb
Labels: bugfix

#2079 (FACT-2634) Acceptance test that verifies facter behaviour with custom files
  acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_api.rb
  acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_cli.rb
Labels: maintenance

#2095 (FACT-2803) Detect hypervisors as amazon if virtwhat detects aws.
  lib/facter/facts/linux/ec2_metadata.rb
  spec/facter/facts/linux/ec2_metadata_spec.rb
Labels: bugfix

#2087 (FACT-2748) Fix fact types on all platforms-Part 1
  lib/facter/facts/aix/hypervisors/lpar.rb
  lib/facter/facts/linux/identity/gid.rb
  lib/facter/facts/linux/identity/uid.rb
  lib/facter/facts/linux/is_virtual.rb
  lib/facter/facts/linux/memory/swap/available_bytes.rb
  lib/facter/facts/linux/memory/swap/total_bytes.rb
  lib/facter/facts/linux/memory/swap/used_bytes.rb
  lib/facter/facts_utils/unit_converter.rb
  lib/facter/resolvers/fips_enabled_resolver.rb
  lib/facter/resolvers/identity_resolver.rb
  lib/facter/resolvers/linux/load_averages.rb
  lib/facter/resolvers/memory_resolver.rb
  spec/facter/facts/aix/hypervisors/lpar_spec.rb
  spec/facter/facts/aix/memory/swap/available_bytes_spec.rb
  spec/facter/facts/aix/memory/swap/total_bytes_spec.rb
  spec/facter/facts/aix/memory/system/available_bytes_spec.rb
  spec/facter/facts/aix/memory/system/total_bytes_spec.rb
  spec/facter/facts/freebsd/memory/swap/available_bytes_spec.rb
  spec/facter/facts/freebsd/memory/swap/total_bytes_spec.rb
  spec/facter/facts/freebsd/memory/system/available_bytes_spec.rb
  spec/facter/facts/freebsd/memory/system/total_bytes_spec.rb
  spec/facter/facts/linux/is_virtual_spec.rb
  spec/facter/facts/linux/memory/swap/available_bytes_spec.rb
  spec/facter/facts/linux/memory/swap/total_bytes_spec.rb
  spec/facter/facts/linux/memory/swap/used_bytes_spec.rb
  spec/facter/facts/linux/memory/system/available_bytes_spec.rb
  spec/facter/facts/linux/memory/system/total_bytes_spec.rb
  spec/facter/facts/macosx/memory/swap/available_bytes_spec.rb
  spec/facter/facts/macosx/memory/swap/total_bytes_spec.rb
  spec/facter/facts/macosx/memory/system/available_bytes_spec.rb
  spec/facter/facts/macosx/memory/system/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/total_bytes_spec.rb
  spec/facter/facts/windows/memory/system/available_bytes_spec.rb
  spec/facter/facts/windows/memory/system/total_bytes_spec.rb
  spec/facter/facts_utils/unit_converter_spec.rb
  spec/facter/resolvers/fips_enabled_resolver_spec.rb
  spec/facter/resolvers/identity_resolver_spec.rb
  spec/facter/resolvers/linux/load_averages_spec.rb
  spec/facter/resolvers/memory_resolver_spec.rb
  spec/fixtures/rhel5_memory
Labels: maintenance

#2101 (maint) add support for redhat-8-arm64 (main)
  acceptance/tests/facts/networking_facts.rb
Labels: maintenance

#2098 (FACT-2748) Fixed type for blockdevice_*_size
  lib/facter/facts/linux/disks.rb
  spec/facter/facts/linux/disks_spec.rb
Labels: bugfix

#2102 (FACT-2317) Add Facter.define_fact method
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: feature

#2099 (FACT-2782) monkey-patch sys-filesystem until a new version is released
  lib/facter/patches/sysfilesystem/sys/statvfs.rb
  lib/facter/resolvers/utils/filesystem_helper.rb
Labels: maintenance

#2080 (FACT-2793) Time limit for Facter::Core::Execute
  .rubocop_todo.yml
  acceptance/tests/custom_facts/time_limit_for_execute_command.rb
  lib/facter/custom_facts/core/execution/base.rb
  lib/facter/facts/aix/kernel.rb
  lib/facter/facts/aix/kernelmajversion.rb
  lib/facter/facts/aix/kernelrelease.rb
  lib/facter/facts/aix/kernelversion.rb
  lib/facter/facts/aix/os/release.rb
  lib/facter/resolvers/aix/os_level.rb
  lib/facter/resolvers/aix/os_level_resolver.rb
  lib/facter/resolvers/os_level_resolver.rb
  spec/custom_facts/core/execution/fact_manager_spec.rb
  spec/facter/facts/aix/kernel_spec.rb
  spec/facter/facts/aix/kernelmajversion_spec.rb
  spec/facter/facts/aix/kernelrelease_spec.rb
  spec/facter/facts/aix/kernelversion_spec.rb
  spec/facter/facts/aix/os/release_spec.rb
  spec/facter/resolvers/aix/os_level_spec.rb
  spec/facter/resolvers/lsb_release_resolver_spec.rb
  spec/facter/resolvers/os_level_resolver_spec.rb
  spec/facter/resolvers/partitions_spec.rb
Labels: bugfix

#2100 FACT(2326) Add Facter.each method
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: feature

#2103 (FACT-2324) Add loadfacts API method
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: feature

#2104 (maint) Changelog for 4.0.39 release
  CHANGELOG.md
Labels: maintenance

#2106 (FACT-2816) - Fix ec2 fact issues when on non ec2 systems
  lib/facter/facts/linux/ec2_metadata.rb
  lib/facter/facts/linux/ec2_userdata.rb
  spec/facter/facts/linux/ec2_metadata_spec.rb
  spec/facter/facts/linux/ec2_userdata_spec.rb
Labels: bugfix, community

#2108 (FACT-2799) Fix fact loading for nested fact calls
  lib/facter/framework/core/fact_loaders/fact_loader.rb
Labels: bugfix

#2107 (FACT-2432) Fixed environment dependant tests
  lib/facter/framework/core/options/option_store.rb
  spec/framework/core/options/option_store_spec.rb
Labels: maintenance

#2105 (FACT-2798) Set color to true, fix Facter.log_exception
  acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_api.rb
  acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_cli.rb
  acceptance/tests/custom_facts/time_limit_for_execute_command.rb
  acceptance/tests/options/verbose.rb
  lib/facter.rb
  lib/facter/framework/core/options/option_store.rb
  lib/facter/framework/logging/logger.rb
  spec/facter/facter_spec.rb
  spec/facter/util/file_helper_spec.rb
  spec/framework/core/options/option_store_spec.rb
  spec/framework/logging/logger_spec.rb
  spec/spec_helper.rb
Labels: bugfix

#2089 (FACT-2786) Fix fact caching if fact is defined in multiple groups
  acceptance/tests/custom_facts/cached_custom_fact.rb
  acceptance/tests/custom_facts/weighted_cached_custom_facts.rb
  acceptance/tests/options/config_file/ttls_cached_fact_in_multiple_groups.rb
  acceptance/tests/options/config_file/ttls_cached_individual_fact_name.rb
  lib/facter/custom_facts/util/directory_loader.rb
  lib/facter/framework/config/fact_groups.rb
  lib/facter/framework/core/cache_manager.rb
  spec/facter/cache_manager_spec.rb
Labels: bugfix

#2111 (maint) Fix for blockdevice_*_size legacy fact on Aix and Solaris
  lib/facter/facts/aix/disks.rb
  lib/facter/facts/solaris/disks.rb
  spec/facter/facts/aix/disks_spec.rb
  spec/facter/facts/solaris/disks_spec.rb
Labels: bugfix

#2110 (FACT-2812) 4.0.40 Changelog
  CHANGELOG.md
Labels: maintenance
