Repository puppetlabs/facter, pull requests merged in 2020-12, with the labels that each got.

#2203 (FACT-2883) Log resolved facts
  lib/facter/framework/core/fact_manager.rb
Labels: bugfix

#2210 (maint) Add debug message containing Facter Version
  lib/facter.rb
Labels: maintenance

#2196 (FACT-2859) Implement load_external API method
  acceptance/tests/facter_load_external.rb
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: bugfix

#2212 (maint) Add guard agains no user query
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: maintenance

#2208 (FACT-2882) Fix fqdn on Linux
  lib/facter/resolvers/hostname_resolver.rb
  spec/facter/resolvers/hostname_resolver_spec.rb
Labels: bugfix

#2220 (packaging) Bump to version '4.0.47' [no-promote]
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2218 (FACT-2894) Facter fails to retrieve fqdn
  lib/facter/resolvers/hostname_resolver.rb
  spec/facter/resolvers/hostname_resolver_spec.rb
Labels: bugfix

#2216 (maint) Catch exceptions from resolvers and log debug message
  lib/facter/framework/logging/logger.rb
  lib/facter/resolvers/base_resolver.rb
  spec/facter/resolvers/aix/serialnumber_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: maintenance

#2221 (FACT-2891) Fix OpenVz detection
  lib/facter/resolvers/open_vz.rb
  spec/facter/resolvers/open_vz_spec.rb
Labels: bugfix

#2215 (FACT-2884) Do not attempt to resolve facts passed as env vars
  lib/facter/custom_facts/util/collection.rb
  lib/facter/custom_facts/util/loader.rb
  lib/facter/custom_facts/util/resolution.rb
  lib/facter/framework/core/fact_loaders/external_fact_loader.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
  lib/facter/models/loaded_fact.rb
  spec/custom_facts/util/collection_spec.rb
  spec/custom_facts/util/loader_spec.rb
  spec/framework/core/fact_loaders/external_fact_loader_spec.rb
  spec/framework/core/fact_loaders/fact_loader_spec.rb
Labels: bugfix

#2217 (maint) Extracted primary interface to util class
  lib/facter/resolvers/networking_linux_resolver.rb
  lib/facter/resolvers/solaris/networking.rb
  lib/facter/util/resolvers/networking/primary_interface.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
  spec/facter/util/resolvers/networking/primary_interface_spec.rb
  spec/fixtures/ip_route_show_default
  spec/fixtures/proc_net_route
  spec/fixtures/route_n_get_default
Labels: maintenance

#2223 (maint) Skip ssh-key types we don't support
  lib/facter/resolvers/ssh_resolver.rb
  lib/facter/util/resolvers/ssh_helper.rb
  spec/facter/resolvers/ssh_resolver_spec.rb
Labels: bugfix

#2224 (maint) to_hash API method should return a hash
  lib/facter.rb
  spec/facter/facter_spec.rb
Labels: bugfix

#2209 (FACT-2874) Load external facts in lexicographical order
  acceptance/tests/external_facts/files_containing_external_facts_are_loaded_in_lexicographical_order.rb
  lib/facter/custom_facts/util/directory_loader.rb
  lib/facter/custom_facts/util/fact.rb
Labels: bugfix

#2222 (FACT-2892) Add extra search for primary interface
  .rubocop.yml
  lib/facter/resolvers/networking_resolver.rb
  lib/facter/resolvers/solaris/networking.rb
  lib/facter/util/resolvers/networking/networking.rb
  lib/facter/util/resolvers/networking/primary_interface.rb
  spec/facter/resolvers/networking_resolver_spec.rb
  spec/facter/util/resolvers/networking/primary_interface_spec.rb
  spec/fixtures/proc_net_route_empty
Labels: bugfix

#2206 (FACT-2306) Added option to use AWS IMDSv2
  lib/facter/resolvers/ec2.rb
  lib/facter/util/resolvers/aws_token.rb
  lib/facter/util/resolvers/http.rb
  spec/facter/util/resolvers/aws_token_spec.rb
  spec/facter/util/resolvers/http_spec.rb
Labels: feature

#2225 (maint) Fix facter name in readme
  README.md
Labels: maintenance

#2226 (FACT-2898) resolve facts sequential by default
  lib/facter/framework/core/options/option_store.rb
  spec/framework/core/options/option_store_spec.rb
Labels: maintenance

#2227 (FACT-2892) Fixes for primary interface on solaris 11
  lib/facter/resolvers/solaris/networking.rb
  lib/facter/util/resolvers/networking/dhcp.rb
Labels: bugfix

#2229 (maint) Catch exceptions when resolving mac, this can happen on Jruby
  lib/facter/resolvers/networking_linux_resolver.rb
Labels: bugfix

#2228 (FACT-2874) check for fact_type method before usage
  lib/facter/custom_facts/util/fact.rb
Labels: bugfix

#2230 (maint) Fix fqdn on JRuby
  lib/facter/resolvers/hostname_resolver.rb
Labels: bugfix

#2236 (packaging) Bump to version '4.0.48' [no-promote]
  agent/facter-ng.gemspec
  facter.gemspec
Labels: maintenance

#2238 (FACT-2903) Fix blockdevices facts
  lib/facter/facts/aix/disks.rb
  lib/facter/facts/linux/disks.rb
  lib/facter/facts/solaris/disks.rb
Labels: bugfix
