Repository puppetlabs/facter, pull requests merged in 2020-08, with the labels that each got.

#2004 (FACT-2735) virtual not working on EXADATA baremetal
  lib/facter/facts/linux/virtual.rb
  lib/facter/resolvers/lspci.rb
  spec/facter/resolvers/lspci_spec.rb
Labels: bugfix

#2008 (FACT-2736) networking facts don't work on EXADATA baremetal
  lib/facter/resolvers/networking_linux_resolver.rb
  lib/facter/resolvers/utils/networking.rb
  lib/facter/resolvers/windows/networking_resolver.rb
Labels: bugfix

#1999 (FACT-2040) Added solaris memory resolver
  lib/facter/facts/solaris/memory/swap/available.rb
  lib/facter/facts/solaris/memory/swap/available_bytes.rb
  lib/facter/facts/solaris/memory/swap/capacity.rb
  lib/facter/facts/solaris/memory/swap/total.rb
  lib/facter/facts/solaris/memory/swap/total_bytes.rb
  lib/facter/facts/solaris/memory/swap/used.rb
  lib/facter/facts/solaris/memory/swap/used_bytes.rb
  lib/facter/facts/solaris/memory/system/available.rb
  lib/facter/facts/solaris/memory/system/available_bytes.rb
  lib/facter/facts/solaris/memory/system/capacity.rb
  lib/facter/facts/solaris/memory/system/total.rb
  lib/facter/facts/solaris/memory/system/total_bytes.rb
  lib/facter/facts/solaris/memory/system/used.rb
  lib/facter/facts/solaris/memory/system/used_bytes.rb
  lib/facter/resolvers/solaris/memory.rb
  spec/facter/facts/solaris/memory/swap/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/available_spec.rb
  spec/facter/facts/solaris/memory/swap/capacity_spec.rb
  spec/facter/facts/solaris/memory/swap/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/total_spec.rb
  spec/facter/facts/solaris/memory/swap/used_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/used_spec.rb
  spec/facter/facts/solaris/memory/system/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/available_spec.rb
  spec/facter/facts/solaris/memory/system/capacity_spec.rb
  spec/facter/facts/solaris/memory/system/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/total_spec.rb
  spec/facter/facts/solaris/memory/system/used_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/used_spec.rb
  spec/facter/resolvers/solaris/memory_spec.rb
  spec/fixtures/kstat_sys_pages
  spec/fixtures/swap_l
Labels: feature

#2010 (FACT-2724) Confine blocks behave differently with Facter 4, causing spec tests to suddenly fail
  lib/facter/facts/macosx/virtual.rb
  spec/facter/facts/macosx/virtual_spec.rb
Labels: bugfix

#2011 (maint) Fixed multiple logs for pagesize call
  lib/facter/resolvers/solaris/memory.rb
Labels: maintenance

#2014 (FACT-2732) OracleLinux 7 and Scientific Linux 7 OS facts incorrect in Facter 4.0.30
  lib/facter/os_hierarchy.json
  lib/facter/resolvers/os_release_resolver.rb
  spec/facter/resolvers/os_release_resolver_spec.rb
  spec/fixtures/debian_os_release
  spec/fixtures/os_release_oracle_linux
Labels: bugfix

#2017 (FACT-2649) Fix ruby 2.7 warning on Facter 4
  lib/facter/resolvers/windows/ffi/ffi.rb
Labels: maintenance

#2015 (FACT-2725) add generate changelog script
  .rubocop.yml
  Gemfile
  Rakefile
  scripts/generate_changelog.rb
Labels: maintenance

#2016 (FACT-2739) Extend os hierarchy to consider multiple os families
  lib/facter/framework/detector/os_detector.rb
  spec/framework/detector/os_detector_spec.rb
Labels: feature

#2013 (FACT-2714) Fix dhcp on solaris 10
  lib/facter/resolvers/solaris/ffi/ffi.rb
  lib/facter/resolvers/solaris/networking_resolver.rb
Labels: bugfix

#2021 Add FreeBSD dmi facts
  lib/facter/facts/freebsd/dmi/bios/release_date.rb
  lib/facter/facts/freebsd/dmi/bios/vendor.rb
  lib/facter/facts/freebsd/dmi/bios/version.rb
  lib/facter/facts/freebsd/dmi/manufacturer.rb
  lib/facter/facts/freebsd/dmi/product/name.rb
  lib/facter/facts/freebsd/dmi/product/serial_number.rb
  lib/facter/facts/freebsd/dmi/product/uuid.rb
  lib/facter/resolvers/freebsd/dmi_resolver.rb
  lib/facter/resolvers/freebsd/ffi/ffi_helper.rb
  spec/facter/facts/freebsd/dmi/bios/release_date_spec.rb
  spec/facter/facts/freebsd/dmi/bios/vendor_spec.rb
  spec/facter/facts/freebsd/dmi/bios/version_spec.rb
  spec/facter/facts/freebsd/dmi/manufacturer_spec.rb
  spec/facter/facts/freebsd/dmi/product/name_spec.rb
  spec/facter/facts/freebsd/dmi/product/serial_number_spec.rb
  spec/facter/facts/freebsd/dmi/product/uuid_spec.rb
  spec/facter/resolvers/freebsd/dmi_bios_resolver_spec.rb
Labels: feature

#2020 Add FreeBSD memory facts
  lib/facter/facts/freebsd/memory/swap/available.rb
  lib/facter/facts/freebsd/memory/swap/available_bytes.rb
  lib/facter/facts/freebsd/memory/swap/capacity.rb
  lib/facter/facts/freebsd/memory/swap/encrypted.rb
  lib/facter/facts/freebsd/memory/swap/total.rb
  lib/facter/facts/freebsd/memory/swap/total_bytes.rb
  lib/facter/facts/freebsd/memory/swap/used.rb
  lib/facter/facts/freebsd/memory/swap/used_bytes.rb
  lib/facter/facts/freebsd/memory/system/available.rb
  lib/facter/facts/freebsd/memory/system/available_bytes.rb
  lib/facter/facts/freebsd/memory/system/capacity.rb
  lib/facter/facts/freebsd/memory/system/total.rb
  lib/facter/facts/freebsd/memory/system/total_bytes.rb
  lib/facter/facts/freebsd/memory/system/used.rb
  lib/facter/facts/freebsd/memory/system/used_bytes.rb
  lib/facter/resolvers/freebsd/swap_memory_resolver.rb
  lib/facter/resolvers/freebsd/system_memory_resolver.rb
  spec/facter/facts/freebsd/memory/swap/available_bytes_spec.rb
  spec/facter/facts/freebsd/memory/swap/available_spec.rb
  spec/facter/facts/freebsd/memory/swap/capacity_spec.rb
  spec/facter/facts/freebsd/memory/swap/encrypted_spec.rb
  spec/facter/facts/freebsd/memory/swap/total_bytes_spec.rb
  spec/facter/facts/freebsd/memory/swap/total_spec.rb
  spec/facter/facts/freebsd/memory/swap/used_bytes_spec.rb
  spec/facter/facts/freebsd/memory/swap/used_spec.rb
  spec/facter/facts/freebsd/memory/system/available_bytes_spec.rb
  spec/facter/facts/freebsd/memory/system/available_spec.rb
  spec/facter/facts/freebsd/memory/system/capacity_spec.rb
  spec/facter/facts/freebsd/memory/system/total_bytes_spec.rb
  spec/facter/facts/freebsd/memory/system/total_spec.rb
  spec/facter/facts/freebsd/memory/system/used_bytes_spec.rb
  spec/facter/facts/freebsd/memory/system/used_spec.rb
  spec/facter/resolvers/freebsd/swap_memory_resolver_spec.rb
  spec/facter/resolvers/freebsd/system_memory_resolver_spec.rb
  spec/fixtures/freebsd_swapinfo
  spec/fixtures/freebsd_vmstat
Labels: feature

#2022 (maint) Fix generate_changelog script
  .rubocop.yml
  scripts/generate_changelog.rb
Labels: maintenance

#2026 (maint) Changelog for release 4.0.34 and version bump
  CHANGELOG.md
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2025 (FACT-2726) Add solaris dmi facts
  acceptance/tests/facts/dmi.rb
  acceptance/tests/facts/productname.rb
  lib/facter/facts/solaris/dmi/bios/release_date.rb
  lib/facter/facts/solaris/dmi/bios/vendor.rb
  lib/facter/facts/solaris/dmi/bios/version.rb
  lib/facter/facts/solaris/dmi/chassis/asset_tag.rb
  lib/facter/facts/solaris/dmi/chassis/type.rb
  lib/facter/facts/solaris/dmi/manufacturer.rb
  lib/facter/facts/solaris/dmi/product/name.rb
  lib/facter/facts/solaris/dmi/product/serial_number.rb
  lib/facter/facts/solaris/dmi/product/uuid.rb
  lib/facter/resolvers/solaris/dmi.rb
  lib/facter/resolvers/solaris/dmi_sparc.rb
  spec/facter/facts/solaris/dmi/bios/release_date_spec.rb
  spec/facter/facts/solaris/dmi/bios/vendor_spec.rb
  spec/facter/facts/solaris/dmi/bios/version_spec.rb
  spec/facter/facts/solaris/dmi/chassis/asset_tag_spec.rb
  spec/facter/facts/solaris/dmi/chassis/type_spec.rb
  spec/facter/facts/solaris/dmi/manufacturer_spec.rb
  spec/facter/facts/solaris/dmi/product/name_spec.rb
  spec/facter/facts/solaris/dmi/product/serial_number_spec.rb
  spec/facter/facts/solaris/dmi/product/uuid_spec.rb
  spec/facter/resolvers/solaris/dmi_sparc_spec.rb
  spec/facter/resolvers/solaris/dmi_spec.rb
  spec/fixtures/prtdiag
  spec/fixtures/smbios_bios
  spec/fixtures/smbios_chassis
  spec/fixtures/smbios_system
Labels: feature

#2030 (FACT-2742) Exclude net/https when running on jruby FIPS
  lib/facter/resolvers/base_resolver.rb
  lib/facter/resolvers/ec2.rb
Labels: bugfix

#2024 (FACT-2723) --list-*-groups also displays external facts
  lib/facter/framework/cli/cli.rb
  lib/facter/framework/config/fact_groups.rb
  spec/framework/config/fact_groups_spec.rb
Labels: bugfix

#2031 (FACT-2737) facter uptime shows host uptime inside docker container
  lib/facter/facts/linux/system_uptime/days.rb
  lib/facter/facts/linux/system_uptime/hours.rb
  lib/facter/facts/linux/system_uptime/seconds.rb
  lib/facter/facts/linux/system_uptime/uptime.rb
  lib/facter/resolvers/linux/docker_uptime.rb
  lib/facter/resolvers/linux/load_averages.rb
  lib/facter/resolvers/uptime_resolver.rb
  lib/facter/resolvers/utils/uptime_helper.rb
  spec/facter/facts/linux/system_uptime/days_spec.rb
  spec/facter/facts/linux/system_uptime/hours_spec.rb
  spec/facter/facts/linux/system_uptime/seconds_spec.rb
  spec/facter/facts/linux/system_uptime/uptime_spec.rb
  spec/facter/resolvers/linux/docker_uptime_spec.rb
  spec/facter/resolvers/utils/uptime_helper_spec.rb
Labels: bugfix

#2029 (FACT-2672) Fix ssh fact output
  .rubocop_todo.yml
  lib/facter/facts/aix/ssh.rb
  lib/facter/facts/linux/ssh.rb
  lib/facter/facts/macosx/ssh.rb
  lib/facter/facts/solaris/ssh.rb
  spec/facter/facts/aix/ssh_spec.rb
  spec/facter/facts/linux/ssh_spec.rb
  spec/facter/facts/solaris/ssh_spec.rb
  spec/facter/resolvers/ssh_resolver_spec.rb
Labels: bugfix

#2032 (FACT-2402) Exclude fuseblk from filesystems
  lib/facter/resolvers/filesystems_resolver.rb
  spec/fixtures/filesystems
Labels: bugfix

#2027 (FACT-2722) Add disks fact for Solaris
  lib/facter/facts/solaris/disks.rb
  lib/facter/resolvers/load_averages.rb
  lib/facter/resolvers/solaris/disks.rb
  spec/facter/facts/solaris/disks_spec.rb
  spec/facter/resolvers/solaris/disks_spec.rb
  spec/fixtures/kstat_sderr
Labels: feature

#2036 (maint) Changelog for 4.0.35 release
  CHANGELOG.md
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2033 (FACT-2721) Added Solaris virtual fact
  lib/facter/facts/solaris/virtual.rb
  lib/facter/resolvers/solaris/ldom.rb
  spec/facter/facts/solaris/virtual_spec.rb
  spec/facter/resolvers/solaris/ldom_spec.rb
  spec/fixtures/virtinfo
Labels: feature

#2042 (maint) Add nil check for ec2 facts.
  lib/facter/facts/linux/ec2_metadata.rb
  lib/facter/facts/linux/ec2_userdata.rb
  lib/facter/facts/windows/ec2_metadata.rb
  lib/facter/facts/windows/ec2_userdata.rb
  spec/facter/facts/linux/ec2_metadata_spec.rb
  spec/facter/facts/linux/ec2_userdata_spec.rb
  spec/facter/facts/windows/ec2_metadata_spec.rb
  spec/facter/facts/windows/ec2_userdata_spec.rb
Labels: bugfix

#2043 (maint) Correctly initialise logger.
  lib/facter/resolvers/utils/http.rb
Labels: bugfix

#2041 (FACT-2743) Added LDom fact for solaris
  lib/facter/facts/solaris/ldom.rb
  spec/facter/facts/solaris/ldom_spec.rb
Labels: feature

#2046 (FACT-2561) Fix blocking mechanism
  .rubocop_todo.yml
  lib/facter/framework/core/fact_filter.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
  spec/facter/fact_filter_spec.rb
  spec/framework/core/fact_loaders/fact_loader_spec.rb
Labels: bugfix

#2047 (FACT-2296) Added fact group for legacy facts
  lib/facter/fact_groups.conf
Labels: feature

#2034 (FACT-2747) Add missing legacy facts on all platforms
  lib/facter/facts/aix/disks.rb
  lib/facter/facts/aix/sshfp_algorithm.rb
  lib/facter/facts/freebsd/sshfp_algorithm.rb
  lib/facter/facts/linux/disks.rb
  lib/facter/facts/linux/processors/speed.rb
  lib/facter/facts/linux/sshfp_algorithm.rb
  lib/facter/facts/macosx/sshfp_algorithm.rb
  lib/facter/facts/solaris/disks.rb
  lib/facter/facts/solaris/sshfp_algorithm.rb
  lib/facter/facts/solaris/zones.rb
  lib/facter/facts/windows/sshfp_algorithm.rb
  lib/facter/resolvers/processors_resolver.rb
  spec/facter/facts/aix/disks_spec.rb
  spec/facter/facts/aix/sshfp_algorithm_spec.rb
  spec/facter/facts/freebsd/sshfp_algorithm_spec.rb
  spec/facter/facts/linux/disks_spec.rb
  spec/facter/facts/linux/processors/speed_spec.rb
  spec/facter/facts/linux/sshfp_algorithm_spec.rb
  spec/facter/facts/macosx/sshfp_algorithm_spec.rb
  spec/facter/facts/solaris/disks_spec.rb
  spec/facter/facts/solaris/sshfp_algorithm_spec.rb
  spec/facter/facts/solaris/zones_spec.rb
  spec/facter/facts/windows/sshfp_algorithm_spec.rb
  spec/facter/resolvers/processors_resolver_spec.rb
  spec/fixtures/cpuinfo_powerpc
Labels: feature

#2050 (FACT-2753) Resolve facts sequentially.
  lib/facter/framework/core/fact/internal/core_fact.rb
  lib/facter/framework/core/fact/internal/internal_fact_manager.rb
Labels: feature

#2049 (FACT-2514) External facts with no output will be logged with debug
  lib/facter/custom_facts/util/directory_loader.rb
  spec/custom_facts/util/directory_loader_spec.rb
Labels: maintenance

#2045 (FACT-2728) Added hypervisors fact for Solaris
  lib/facter/facts/solaris/hypervisors/ldom.rb
  lib/facter/facts/solaris/hypervisors/zone.rb
  spec/facter/facts/solaris/hypervisors/ldom_spec.rb
  spec/facter/facts/solaris/hypervisors/zone_spec.rb
Labels: feature

#2052 (FACT-2752) Added serialnumber fact for AIX
  lib/facter/facts/aix/serialnumber.rb
  lib/facter/resolvers/aix/serialnumber.rb
  spec/facter/facts/aix/serialnumber_spec.rb
  spec/facter/resolvers/aix/serialnumber_spec.rb
Labels: feature

#2038 (FACT-2454) fix how used memory is calculated
  lib/facter/resolvers/memory_resolver.rb
  spec/facter/resolvers/memory_resolver_spec.rb
Labels: bugfix

#2053 (FACT-2741) Fix double quotes for numbers in yaml formatter
  lib/facter/framework/formatters/yaml_fact_formatter.rb
  spec/framework/formatters/yaml_fact_formatter_spec.rb
Labels: bugfix
