Repository puppetlabs/facter, pull requests merged in 2021-01, with the labels that each got.

#2239 (FACT-2902) Correctly detect family for Linux
  lib/facter/facts/linux/os/family.rb
  lib/facter/framework/detector/os_detector.rb
  lib/facter/util/facts/facts_utils.rb
  spec/facter/util/facts/facts_utils_spec.rb
Labels: bugfix

#2235 (FACT-2900) Add acceptance test for aggregate resolution facts
  acceptance/tests/custom_facts/custom_facts_aggregate_resolutions.rb
Labels: maintenance

#2243 (FACT-2899) Fix code coverage
  spec/spec_helper.rb
Labels: maintenance

#2234 (FACT-2862) Add acceptance test for caching core and custom fact in the same group
  acceptance/tests/options/config_file/ttls/cached_custom_group_core_custom_facts.rb
Labels: maintenance

#2199 (FACT-2858) Added acceptance test for migrating from facter 3
  acceptance/tests/options/config_file/cache_migrate_from_facter_3.rb
Labels: maintenance

#2245 (FACT-2882) Fix domain fact on Windows
  lib/facter/facts/windows/networking/fqdn.rb
  lib/facter/resolvers/windows/networking.rb
  spec/facter/facts/windows/networking/fqdn_spec.rb
  spec/facter/resolvers/windows/networking_spec.rb
Labels: bugfix

#2246 (FACT-2909) Fixed --hocon option
  acceptance/tests/options/hocon.rb
  lib/facter/framework/core/options/option_store.rb
  spec/framework/core/options/option_store_spec.rb
Labels: bugfix

#2247 README.md: remove nonexistent create_fact rake task
  README.md
Labels: community, maintenance

#2237 (FACT-2901) Refactor linux networking resolver and add unit tests
  .rubocop.yml
  .rubocop_todo.yml
  acceptance/tests/facts/networking_facts_with_secondary_ips.rb
  acceptance/tests/facts/networking_facts_with_vlans.rb
  lib/facter/resolvers/networking_linux.rb
  lib/facter/util/resolvers/networking.rb
  spec/facter/resolvers/networking_linux_spec.rb
  spec/fixtures/bond_interface_data
  spec/fixtures/ip_-6_route_show
  spec/fixtures/ip_a_invalid_ip
  spec/fixtures/ip_a_linux
  spec/fixtures/ip_a_linux_with_127_first
  spec/fixtures/ip_a_with_labels
  spec/fixtures/ip_a_with_peer
  spec/fixtures/ip_a_with_vlan
  spec/fixtures/ip_link_show
  spec/fixtures/ip_link_show_bond0_bonded
  spec/fixtures/ip_link_show_bonded
  spec/fixtures/ip_link_show_ens160
  spec/fixtures/ip_link_show_eth2_bonded
  spec/fixtures/ip_link_show_eth3_bonded
  spec/fixtures/ip_link_show_lo
  spec/fixtures/ip_route_get_1_linux
  spec/fixtures/ip_route_get_1_linux_not_cached
  spec/fixtures/ip_route_show
  spec/mocks/ffi.rb
  spec/mocks/kernel.rb
  spec/mocks/socket.rb
  spec/mocks/sys_filesystem.rb
  spec/mocks/win32.rb
  spec/mocks/win32_registry_error.rb
  spec/mocks/win32ole.rb
Labels: maintenance

#2251 (maint)Enable puppet facts to disable legacy facts
  lib/facter.rb
  spec/facter/facter_spec.rb
  spec_integration/facter_resolve_spec.rb
  spec_integration/facter_values_spec.rb
Labels: maintenance

#2250 (FACT-2911) Improve regex for detecting legacy processor facts
  lib/facter/config.rb
  spec_integration/facter_block_legacy_spec.rb
  spec_integration/integration_helper.rb
Labels: bugfix

#2252 (maint) fix execution tests on windows
  acceptance/tests/options/config_file/no_custom_facts_and_load_path.rb
  acceptance/tests/options/custom_facts_load_path.rb
  acceptance/tests/options/no_custom_facts_and_load_path.rb
Labels: maintenance

#2253 (maint) Fix puppet facts acceptance
  acceptance/tests/options/config_file/ttls_puppet_facts_honors_cached_facts.rb
Labels: maintenance

#2254 (maint) Add debug message
  lib/facter/custom_facts/util/fact.rb
  lib/facter/custom_facts/util/resolution.rb
Labels: maintenance

#2257 (FACT-2919) fix fact location debug message
  acceptance/tests/custom_facts/custom_facts_aggregate_resolutions.rb
  lib/facter/custom_facts/core/aggregate.rb
  lib/facter/custom_facts/util/fact.rb
Labels: bugfix

#2258 (maint) bump version to 4.0.50
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2260 (FACT-2923) Retrieve domain priority from registry
  lib/facter/resolvers/windows/networking.rb
  spec/facter/resolvers/windows/networking_spec.rb
Labels: bugfix

#2261 (FACT-2924) Facter fails with invalid config file
  lib/facter/framework/config/config_reader.rb
  spec/framework/config/config_reader_spec.rb
Labels: bugfix

#2259 (FACT-2917) Blocking `legacy` facts slows down facter
  lib/facter/framework/config/fact_groups.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
  spec/framework/config/fact_groups_spec.rb
  spec/framework/core/fact_loaders/fact_loader_spec.rb
Labels: bugfix

#2233 (FACT-2861) Added extra test case for partial cache invalidation
  acceptance/tests/options/config_file/ttls_cache_system_uptime.rb
Labels: maintenance

#2197 (FACT-2857) Added acceptance test for user query scenario
  acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
Labels: maintenance

#2263 (FACT-2925) Remove Utils.deep_copy
  lib/facter/custom_facts/util/fact.rb
  lib/facter/framework/core/fact_loaders/external_fact_loader.rb
  lib/facter/util/utils.rb
Labels: maintenance

#2264 (FACT-2927) Fix computation of metrics prefix
  lib/facter/util/facts/unit_converter.rb
  spec/facter/util/facts/unit_converter_spec.rb
Labels: bugfix
