Repository puppetlabs/facter, pull requests merged in 2021-02, with the labels that each got.

#2267 (FACT-2878) AIX networking resolver rewrite
  .rubocop.yml
  lib/facter/resolvers/aix/ffi/ffi.rb
  lib/facter/resolvers/aix/ffi/ffi_helper.rb
  lib/facter/resolvers/aix/ffi/structs.rb
  lib/facter/resolvers/aix/load_averages.rb
  lib/facter/resolvers/aix/networking.rb
  lib/facter/resolvers/windows/ffi/network_utils.rb
  spec/facter/resolvers/aix/ffi_helper_spec.rb
  spec/facter/resolvers/aix/load_averages_spec.rb
  spec/facter/resolvers/aix/networking_spec.rb
  spec/mocks/ffi.rb
Labels: bugfix

#2271 (FACT-2934)Set last exit code after Execution.exec
  .rubocop.yml
  acceptance/tests/custom_facts/execution_execute_sets_status_env_variable.rb
  custom_facts/my_custom_fact.rb
  lib/facter/custom_facts/core/execution/base.rb
  lib/facter/custom_facts/core/execution/popen3.rb
  spec/custom_facts/core/execution/fact_manager_spec.rb
  spec/facter/resolvers/lsb_release_spec.rb
Labels: bugfix

#2277 (maint) bump version to 4.0.51
  agent/facter-ng.gemspec
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2278 (FACT-2818) Add -p option similar to the one from facter 3.
  .rubocop.yml
  lib/facter.rb
  lib/facter/framework/cli/cli.rb
  lib/facter/framework/core/options/option_store.rb
  lib/facter/framework/logging/logger.rb
  spec/framework/core/options/option_store_spec.rb
Labels: feature

#2274 (maint) fix presuite.rb exitstatus
  .github/actions/presuite.rb
Labels: maintenance

#2282 (maint) bump rtc to 0.3.1
  .github/workflows/checks.yaml
Labels: maintenance

#2281 (maint) remove unsupported OSs from base_fact_utils
  acceptance/lib/facter/acceptance/base_fact_utils.rb
Labels: maintenance

#2283 (DOC-4857) Add script for generating man pages in docs.
  lib/docs/generate_cli.rb
Labels: feature

#2286 (maint) Add subcommands to manual and update man pages
  lib/facter/framework/cli/cli.rb
  lib/facter/templates/man.erb
  man/man8/facter.8
Labels: maintenance

#2290 (FACT-2926) Ensure all methods have rubydocs
  lib/facter.rb
  lib/facter/custom_facts/core/aggregate.rb
  lib/facter/custom_facts/core/resolvable.rb
  lib/facter/custom_facts/util/resolution.rb
Labels: maintenance

#2285 (FACT-2937) Update Facter.resolve and fact filtering
  acceptance/tests/custom_facts/custom_fact_with_legacy_fact.rb
  facter.conf
  lib/facter.rb
  lib/facter/framework/cli/cli.rb
  lib/facter/framework/core/fact_filter.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
  lib/facter/framework/core/fact_manager.rb
  lib/facter/framework/core/options.rb
  lib/facter/framework/core/options/option_store.rb
  spec/facter/fact_filter_spec.rb
  spec/facter/facter_spec.rb
  spec/framework/core/options/option_store_spec.rb
  spec/framework/core/options_spec.rb
  spec_integration/facter_resolve_spec.rb
  spec_integration/facter_values_spec.rb
Labels: bugfix

#2289 gemspec: add homepage metadata
  facter.gemspec
Labels: community, maintenance

#2284 (FACT-2947) On Solaris, don't hardcode libsocket path
  lib/facter/resolvers/solaris/ffi/functions.rb
Labels: bugfix, community
