Repository puppetlabs/facter, pull requests merged in 2021-03, with the labels that each got.

#2291 (FACT-2134) Distinguish between CentOS and CentOS Stream
  lib/facter/resolvers/os_release.rb
  spec/facter/resolvers/os_release_spec.rb
  spec/fixtures/os_release_centos
  spec/fixtures/os_release_centos_stream
Labels: community, feature

#2296 (FACT-2944)Facter fails retrieving fqdn with jruby
  .rubocop.yml
  lib/facter/facts/linux/networking/domain.rb
  lib/facter/resolvers/linux/hostname.rb
  lib/facter/util/resolvers/ffi/hostname.rb
  spec/facter/facts/linux/networking/domain_spec.rb
  spec/facter/resolvers/linux/hostname_spec.rb
Labels: bugfix

#2305 (FACT-2952) Align the lsbmajdistrelease fact with Facter 3
  lib/facter/facts/ubuntu/lsbdistrelease.rb
  spec/facter/facts/linux/lsbdistrelease_spec.rb
  spec/facter/facts/ubuntu/lsbdistrelease_spec.rb
Labels: bugfix

#2301 (FACT-2950) return root fact if defined
  .rubocop.yml
  lib/facter/framework/parsers/query_parser.rb
  spec/facter/query_parser_spec.rb
Labels: bugfix

#2304 (FACT-1847) Fix cloud fact implementation for Azure
  lib/facter/facts/linux/cloud.rb
  lib/facter/facts/linux/cloud/provider.rb
  lib/facter/facts/windows/cloud/provider.rb
  lib/facter/resolvers/cloud.rb
  lib/schema/facter.yaml
  spec/facter/facts/linux/cloud/provider_spec.rb
  spec/facter/facts/windows/cloud/provider_spec.rb
  spec/facter/resolvers/cloud_spec.rb
Labels: bugfix

#2310 (FACT-2960)Accept singular variant of time measure
  lib/facter/framework/config/fact_groups.rb
  spec/framework/config/fact_groups_spec.rb
Labels: bugfix

#2312 (FACT-2962) Add all supported time units for ttls
  lib/facter/framework/config/fact_groups.rb
  spec/framework/config/fact_groups_spec.rb
Labels: bugfix

#2313 (FACT-2961) log warning when cannot delete cache
  lib/facter/framework/core/cache_manager.rb
  spec/facter/cache_manager_spec.rb
Labels: bugfix

#2315 (FACT-2944) Retrieve fqdn and hostname facts with ffi
  lib/facter/facts/linux/networking/fqdn.rb
  lib/facter/facts/linux/networking/hostname.rb
  lib/facter/util/resolvers/ffi/hostname.rb
  spec/facter/facts/linux/networking/fqdn_spec.rb
  spec/facter/facts/linux/networking/hostname_spec.rb
Labels: bugfix

#2318 (FACT-2989) load ffi only when needed
  lib/facter/resolvers/linux/hostname.rb
Labels: bugfix

#2319 (FACT-2956) fix loading of env facts
  acceptance/tests/api/value/env_fact.rb
  acceptance/tests/env_fact.rb
  lib/facter/framework/core/fact_loaders/fact_loader.rb
Labels: bugfix

#2316 (FACT-2982) Rework Solaris mountpoints resolver
  lib/facter/facts/solaris/mountpoints.rb
  lib/facter/resolvers/solaris/mountpoints.rb
  spec/facter/facts/solaris/mountpoints_spec.rb
  spec/facter/resolvers/solaris/mountpoints_spec.rb
Labels: bugfix

#2317 (FACT-2988) Only query cloud provider on HyperV
  lib/facter/facts/linux/cloud/provider.rb
  lib/facter/facts/windows/az_metadata.rb
  lib/facter/facts/windows/cloud/provider.rb
  lib/facter/util/resolvers/http.rb
  spec/facter/facts/linux/cloud/provider_spec.rb
  spec/facter/facts/windows/az_metadata_spec.rb
  spec/facter/facts/windows/cloud/provider_spec.rb
Labels: bugfix

#2314 (FACT-2930) Add Date and Time to supported valid types
  lib/facter/custom_facts/util/normalization.rb
  spec/custom_facts/util/normalization_spec.rb
Labels: bugfix

#2321 (FACT-2967) do not round mb values
  lib/facter/resolvers/aix/ffi/ffi_helper.rb
  lib/facter/util/facts/unit_converter.rb
  spec/facter/facts/aix/memory/swap/available_bytes_spec.rb
  spec/facter/facts/aix/memory/swap/total_bytes_spec.rb
  spec/facter/facts/aix/memory/system/available_bytes_spec.rb
  spec/facter/facts/aix/memory/system/total_bytes_spec.rb
  spec/facter/facts/linux/memory/swap/available_bytes_spec.rb
  spec/facter/facts/linux/memory/swap/total_bytes_spec.rb
  spec/facter/facts/linux/memory/system/available_bytes_spec.rb
  spec/facter/facts/linux/memory/system/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/swap/total_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/available_bytes_spec.rb
  spec/facter/facts/solaris/memory/system/total_bytes_spec.rb
  spec/facter/facts/windows/memory/system/available_bytes_spec.rb
  spec/facter/facts/windows/memory/system/total_bytes_spec.rb
  spec/facter/util/facts/unit_converter_spec.rb
Labels: bugfix

#2320 (FACT-2956) Don't filter out false core facts
  lib/facter/framework/core/fact_manager.rb
  spec/framework/core/fact_manager_spec.rb
Labels: bugfix

#2326 (maint) Fix backslashes in man
  lib/facter/templates/man.erb
  man/man8/facter.8
Labels: maintenance

#2327 (FACT-2997) continue searching when cannot load ffi
  lib/facter/resolvers/linux/hostname.rb
  spec/facter/resolvers/linux/hostname_spec.rb
Labels: bugfix
