Repository puppetlabs/facter, pull requests merged in 2023-12, with the labels that each got.

#2651 (PUP-8241) Use organizational CONTRIBUTING.md
  CONTRIBUTING.md
Labels: maintenance

#2650 (FACT-3452) Make Xen resolver more strict
  lib/facter/resolvers/xen.rb
  spec/facter/resolvers/xen_spec.rb
Labels: bug

#2655 Eliminate redundant token joining and const_get calls
  docs/data-flow.md
  lib/facter/framework/core/fact_loaders/class_discoverer.rb
  lib/facter/framework/parsers/query_parser.rb
Labels: bug

#2656 (FACT-3110) Support for ecdsa 384 and 521 bit keys
  lib/facter/util/resolvers/fingerprint.rb
  lib/facter/util/resolvers/ssh.rb
  lib/facter/util/resolvers/ssh_helper.rb
  spec/facter/resolvers/ssh_spec.rb
  spec/facter/util/resolvers/ssh_helper_spec.rb
  spec/fixtures/ecdsa384
  spec/fixtures/ecdsa384_key
  spec/fixtures/ecdsa521
  spec/fixtures/ecdsa521_key
Labels: enhancement

#2657 Remove Rubocop TODO action
  .github/workflows/checks.yaml
Labels: maintenance

#2653 (FACT-3451) extend amazon linux os release fact
  .rubocop.yml
  lib/facter/facts/amzn/os/distro/release.rb
  lib/facter/facts/amzn/os/release.rb
  lib/facter/framework/core/file_loader.rb
  lib/facter/resolvers/amzn/os_release_rpm.rb
  lib/facter/util/facts/facts_utils.rb
  spec/facter/facts/amzn/os/distro/release_spec.rb
  spec/facter/facts/amzn/os/release_spec.rb
  spec/facter/resolvers/amzn/os_release_rpm_spec.rb
  spec/facter/util/facts/facts_utils_spec.rb
Labels: enhancement
