Repository puppetlabs/facter, pull requests merged in 2024-06, with the labels that each got.

#2728 Update Beaker to 6 and beaker-puppet to 4
  acceptance/Gemfile
Labels: maintenance

#2664 feat(processor.extensions) Add support for CPU flag detection
  lib/facter/facts/linux/processors/extensions.rb
  lib/facter/framework/core/file_loader.rb
  lib/facter/resolvers/processors.rb
  spec/facter/resolvers/processors_spec.rb
Labels: enhancement

#2724 Allow facter test log to be written to a file
  spec/spec_helper.rb
Labels: enhancement

#2574 (FACT-3202) Add is_virtual and virtual support for crio
  lib/facter/framework/core/file_loader.rb
  lib/facter/resolvers/containers.rb
  lib/facter/util/file_helper.rb
  lib/facter/util/linux/proc.rb
  spec/facter/resolvers/containers_spec.rb
  spec/facter/util/file_helper_spec.rb
  spec/facter/util/linux/proc_spec.rb
  spec/fixtures/proc_environ_no_value
  spec/fixtures/proc_environ_podman
Labels: enhancement

#2734 (FACT-3463) Add server to mountpoint device for AIX
  lib/facter/resolvers/aix/mountpoints.rb
  spec/facter/resolvers/aix/mountpoints_spec.rb
Labels: bug

#2483 (FACT-3114) Arch Linux: Implement os version facts
  lib/facter/config.rb
  lib/facter/facts/archlinux/os/release.rb
  lib/facter/framework/core/file_loader.rb
  lib/facter/framework/detector/os_detector.rb
Labels: enhancement

#2735 (packaging) Bump to version '4.8.0' [no-promote]
  facter.gemspec
  lib/facter/version.rb
Labels: maintenance

#2733 (FACT-3205) Ignore ENOENT when cleaning up temporary test files
  .rubocop.yml
  spec/custom_facts/puppetlabs_spec/files.rb
Labels: maintenance

#2736 Use bundler-cache to speed up CI
  .github/workflows/checks.yaml
  .github/workflows/coverage.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/unit_tests.yaml
Labels: maintenance
